curl \
  -H 'Content-Type: application/json' \
  -d '{"contents":[{"parts":[{"text":"create a pure data patch"}]}]}' \
  -X POST 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=<apikey>'